fix(security): fixes #352 - console errors
molgenis/molgenis-frontend pull request #367
Opened 2020-09-09 07:24 UTC by MaxPostema

closes: #352

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [ ] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] Conventional commits (squash if needed)
- [ ] No warnings during install
- [ ] Updated javascript typing

2020-09-09 07:28 UTC, connoratrug commented on packages/security/src/store/getters.ts
> +  hasSuperUserRights: (state: SecurityModel, getters: any): boolean => {
nice, maybe we should add these to the ui-context getters

2020-09-16 07:58 UTC, connoratrug requested changes
Seems to have 2 sources of user rights now ( one in main store and one from context), one from main store should probably be removed in favour of  context ui source.

2020-10-06 11:34 UTC, jelmerveen approved these changes

2020-10-07 08:52 UTC, connoratrug approved these changes

2020-10-07 09:01 UTC, merged